Avoid mypy error on adding newGraph from cache to graph
Fixes:

```
gxformat2/schema/v19_09.py:167: error: Argument 1 to "__iadd__" of "Graph" has incompatible type "Union[str, Graph, bool]"; expected "Iterable[Tuple[Node, Node, Node]]"  [arg-type]
```
and should also be a little more helpful when the external schema can't
be parsed or fetched (not familiar with the code base, but isn't there a
need to be more transparent about this??).