Add missing options to schema-salad-tool
which were available in schema-salad-doc. Fix:

```
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/nsoranzo_gxformat2/.venv/bin/schema-salad-tool", line 8, in <module>
    sys.exit(main())
  File "schema_salad/main.py", line 257, in main
  File "schema_salad/makedoc.py", line 740, in makedoc
AttributeError: 'Namespace' object has no attribute 'brandinverse'
```

when running:

```
schema-salad-tool --print-doc --brandstyle '<link rel="stylesheet" href="https://jamestaylor.org/galaxy-bootstrap/galaxy_bootstrap.css">' --brand '<img src="icon.png" />' --brandlink '' --only https://galaxyproject.org/gxformat2/v19_09#WorkflowDoc --only https://galaxyproject.org/gxformat2/v19_09#GalaxyWorkflow workflow.yml
```